# Filename: Dockerfile

# Base Image
FROM python:latest

# Update
RUN apt-get -y update
RUN apt-get -y install vim nano
RUN apt -y install uvicorn

# Add all python dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# Expose the API endpoint
EXPOSE 5000

# Copy the application files
ADD . .
WORKDIR /app
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]